name: CI using maven and jenkins
on:
 push:
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code on the ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on the ubuntu server
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '11'
         cache: 'maven'
      - name: Test the code
        run: mvn test
      - name: Build the code
        run: mvn package
